# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "114ab8fa7f26210af8e4f8748c3bcd93"
name = "AI Readability 2.0"
handle = "ai-readability-2-0"
application_url = "https://shopify-ai-product-optimizer.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_content,write_content,read_themes,read_customers,read_orders"

[auth]
redirect_urls = [
  "https://shopify-ai-product-optimizer.onrender.com/auth/callback",
  "https://shopify-ai-product-optimizer.onrender.com/auth/shopify/callback", 
  "https://shopify-ai-product-optimizer.onrender.com/api/auth/callback"
]

[pos]
embedded = false
